- hosts: localhost
  vars:
    iam_role_name: AnsibleIAMLambdaRole
    lambda_fn_name: CheckNumberLambdaFunction
  tasks:
    - name: Create {{ iam_role_name }}
      register: lambda_iam_return_value
      community.aws.iam_role:
        name: "{{ iam_role_name }}"
        assume_role_policy_document: "{{ lookup('file','iam-lambda-policy.json') }}"
        state: present
    - name: Show {{ iam_role_name }}.arn
      debug:
        msg: "{{ lambda_iam_return_value.arn }}"     
    - name: Create {{ lambda_fn_name }}
      community.aws.lambda:
        name: "{{ lambda_fn_name }}"
        state: present
        zip_file: 'check-number.zip'
        runtime: 'python3.7'
        role: "{{ lambda_iam_return_value.arn }}"
        handler: 'script.checkNumber'
        tags:
          Name: "{{ lambda_fn_name }}"
