  - hosts: localhost
    tasks:
      - name: Create a role with description and tags
        register: lambda_role
        community.aws.iam_role:
          name: lambda-role
          assume_role_policy_document: "{{ lookup('file','policy.json') }}"
          description: This is My New Role
          state: present
      - name: PythonFunction
        community.aws.lambda:
          name: ansible-deploy-lambda
          state: present
          zip_file: my_lambda_function/my_lambda_function.zip
          runtime: 'python3.9'
          role: "{{ lambda_role.arn }}"
          handler: 'hello_python.my_handler'


