AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: chuxyzbucketdemos001
  HelloLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: HelloLambdaRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
  HelloLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: HelloLambdaFunction
      Role: !GetAtt
        - HelloLambdaRole
        - Arn
      Runtime: python3.7
      Handler: index.my_handler
      Code:
        ZipFile: |
          def my_handler(event, context):
            message = "Hello Lambda World! You passed: " + event['value']
            return message
