AWSTemplateFormatVersion: 2010-09-09
#The Resources
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Description: Creating Amazon S3 bucket from CloudFormation
    Properties:
      BucketName: lestyn-bucket

      # Making the bucket completely private
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

      #Enabling Encryption
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      # Enabling Versioning
      VersioningConfiguration:
        Status: Enabled

#Outputs
Outputs:
  S3Bucket:
    Description: I have created a bucket using this template.
    Value: !Ref S3Bucket