AWSTemplateFormatVersion: 2010-09-09
Description: Creation of a Lambda function and S3 bucket with AWS CloudFormation.
Resources:
  LambdaTestRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSLambdaRole1
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: Role to provide access to lambda
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Description: Amazon lambda function with AWS CloudFormation
      FunctionName: lambdafunction01
      Role: !GetAtt LambdaTestRole.Arn
      Runtime: python3.9
      Handler: index.lambda_handler
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            message = 'Hello {} {}!'.format(event['first_name'], event['last_name'])  
            return { 
                'message' : message
            }

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: s3buckettemplate01
      VersioningConfiguration:
        Status: Enabled